server:
  port: 8080

spring:
  application:
    name: ecommerce

  profiles:
    active: local

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.cache: trace

# swagger-ui
springdoc:
  swagger-ui:
    path: /index.html
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**